### PR TITLE
MacOS build on Travis

### PR DESCRIPTION
**Pull request by henryiii**
Starting a solution to #228

### CODE REVIEW

**Comment by henryiii** [comment]
As expected, the compute backend fails to build on macOS. Rebasing on master to see if that fixes that. There are lots of failing tests on macOS at the moment on OpenCL, as well. I can (temporary, hopefully) disable the failing of a macOS test from indicating an overall failure if you'd like.

**Comment by ddemidov** [comment]
The boost.compute (partial) fix in boostorg/compute#737 is not in 1.65.1, so the fail is to be expected.
And OpenCL failing tests look like OpenCL compiler bugs.

But this PR looks great anyway! Yes, let's mark the MacOS tests as free to fail for now.

**Comment by ddemidov** [comment]
Some OpenCL fails seem to reproduce #92.

**Comment by ddemidov** [comment]
Thanks!

**Pull request merged**
