### PR TITLE
Update intel tools on appveyor script

### PR DESCRIPTION
**Pull request by Zialus**
I was looking for examples of OpenCL projects configured to be tested on appveyor and found yours. I was able to make it work with a few modifications. Now, I'm sharing back those modifications, if you are interested.

### CODE REVIEW

**Comment by Zialus** [comment]
The new windows installer only works with appveyors images: Visual Studio 2013 and Visual Studio 2017

It fails to install on Visual Studio 2015 because it is missing the Universal C Runtime.

**Comment by ddemidov** [comment]
The problem is that with VS 2017 cmake is not  able to find Boost libraries.
(Thank you for the PR by the way)

**Comment by Zialus** [comment]
I think my job here is done. It might be a good idea to report to the appveyor team the C Runtime problem. 

```
Critical: Update for Universal C Runtime in Windows* is not installed.
    Details: Your system is missing an important pre-requisite software update that you must download from Microsoft (KB2999226)
```

**Comment by ddemidov** [comment]
Thanks a lot! I've merged after making a couple of changes (Only kept working VS/Boost combination, and added a couple of environment variables to help cmake find opencl and boost). The tests are still failing, but that looks like an issue with Intel drivers, which I'll need to look at later.

**Pull request merged**
