### PR TITLE
Adding at() for vectors

### LINKED ISSUE #241: at() for vectors
The `at()` method is missing for vectors. Keeping as much of the API consistent for the standard library as possible would be nice!

### PR DESCRIPTION
**Pull request by henryiii**
Fixes #241 .

### CODE REVIEW

**Comment by ddemidov** [comment]
Thanks! Shouldn't `vector::at()` [throw on out of bounds access](http://en.cppreference.com/w/cpp/container/vector/at) though?

**Comment by henryiii** [comment]
Yes, didn't realize the vexcl `[]` didn't throw.

**Comment by henryiii** [comment]
Should be fixed.

**Comment by ddemidov** [comment]
Looks good to me. The travis errors seem to be caused by AMD (they moved the AMDAPPSDK download page somewhere).

**Pull request merged**
